/*
*
*
* */
"use strict"
yx_mallApp.constant('RouterList_Config',[
    {
        name:"tabs",
        url:"/tabs",
        templateUrl:"net/tab.html",
        controller:"tabController",
        files:[
            './js/tabCtrl.js'
        ]
    },{
        name:"tabs.index",
        url:"/_index",
        templateUrl:"net/index.html",
        controller:"indexController",
        files:[
            './js/indexCtrl.js'
        ]
    },{
        name:"tabs.classify",
        url:"/_classify",
        templateUrl:"net/classify.html",
        controller:"classifyController",
        files:[
            './js/classifyCtrl.js'
        ]
    },
    {
        name:"tabs.my",
        url:"_my",
        templateUrl:"net/my.html",
        controller:"myController",
        files:[
            './js/myCtrl.js'
        ]
    },{
        name:"tabs.myOld",
        url:"_myOld",
        templateUrl:"net/my_suge.html",
        controller:"myOldController",
        files:[
            './js/myOldCtrl.js'
        ]
    },{
        name:"tabs.shopCar",
        url:"_shopCar",
        templateUrl:"net/shopCar.html",
        controller:"shopCarController",
        files:[
            './js/shop_carCtrl.js'
        ]
    },{
        name:"tabs.alliance",  //联盟商家
        url:"_alliance",
        templateUrl:"net/allianceMerchant.html",
        controller:"allianceMerchantController",
        files:[
            './js/allianceMerchant.js'

        ]
    },{
        name:"merchantClassify",//商家分类
        url:"/_merchantClassify?classifyId",
        templateUrl:"net/merchantsClassify.html",
        controller:"merchantClassifyController",
        files:[
            './js/merchantClassify.js'
        ]
    },{
        name:"treasure",    //财富
        url:"/_treasure",
        templateUrl:"net/treasure.html",
        controller:"treasureController",
        files:[
            './js/treasure.js'
        ]
    },{
        name:"classifyDetail",
        url:"/_classifyDetail?classifyId",
        templateUrl:"net/classifyDetail.html",
        controller:"classifyDetailController",
        files:[
            './js/classifyDetailCtrl.js'
        ]
    },{
        name:"detail",
        url:"/_detail?goodsId",
        templateUrl:"net/detail.html",
        controller:"detailController",
        files:[
            './js/detailCtrl.js'
        ]
    },{
        name:"clearing",
        url:"/_clearing",
        templateUrl:"net/clearing.html",
        controller:"clearController",
        files:[
            './js/clearCtrl.js'
        ]
    },{
        name:"login",
        url:"/_login",
        templateUrl:"net/login.html",
        controller:"loginController",
        files:[
            './js/loginCtrl.js'
        ]
    },{
        name:"applyWay",
        url:"/_applyWay?OrderID&num&price&point",
        templateUrl:"net/applyWay.html",
        controller:"applyWayController",
        files:[
            './js/applyWayCtrl.js'
        ]
    },{
        name:"address",
        url:"/_address",
        templateUrl:"net/address.html",
        controller:"addressController",
        files:[
            './js/addressCtrl.js'
        ]
    },{
        name:"addAddress",
        url:"/_addAddress",
        templateUrl:"net/addAddress.html",
        controller:"addAddressController",
        files:[
            './js/addAddressCtrl.js'
        ]
    },{
        name:"search",
        url:"/_search",
        templateUrl:"net/search.html",
        controller:"searchController",
        files:[
            './js/searchCtrl.js'
        ]
    },{
        name:"searchDetail",
        url:"/_searchDetail?goodsClass",
        templateUrl:"net/searchDetail.html",
        controller:"searchDetailController",
        files:[
            './js/searchDetailCtrl.js'
        ]
    },{
        name:"myOrder",
        url:"/_myOrder",
        templateUrl:"net/myOrder.html",
        controller:"myOrderController",
        files:[
            './js/myOrderCtrl.js'
        ]
    },{
        name:"upgrade",
        url:"/_upgrade",
        templateUrl:"net/upgrade.html",
        controller:"",
        files:[]
    },
    {
        //联盟订单 审核
        name:"allianceOrderAudit",
        url:"/_allianceOrderAudit",
        templateUrl:"net/allianceOrderAudit.html",
        controller:"allianceOrderAuditController",
        files:[
            './js/allianceOrderAuditCtrl.js'
        ]
    },{
        name:"treasureConversion", //财富  转化
        url:"/_treasureConversion",
        templateUrl:"net/treasureConversion.html",
        controller:"treasureConversionController",
        files:[
            './js/treasureConversion.js'
        ]

    },{
        name:"merchantDetail",//商家 详情
        url:"/_merchantDetail?shopId",
        templateUrl:"net/merchantsDetail.html",
        controller:"merchantDetailController",
        files:[
            './js/merchantDetail.js'
        ]
    },{
        name:"treasurePay",//支付记录
        url:"/_treasurePay",
        templateUrl:"net/treasurePay.html",
        controller:"treasurePayController",
        files:[
            './js/treasurePay.js'
        ]
    },{
        //财富   获赠积分
        name:  "treasureGiven",
        url:"/_treasureGiven",
        templateUrl:"net/treasureGiven.html",
        controller:"treasureGivenController",
        files:[
            './js/treasureGiven.js'
        ]
    },{
        //财富   会员奖励
        name:  "treasureReward",
        url:"/treasureReward",
        templateUrl:"net/treasureReward.html",
        controller:"treasureRewardController",
        files:[
            './js/treasureReward.js'
        ]
    },{
        //财富   购物账单
        name:  "treasureBill",
        url:"/treasureBill",
        templateUrl:"net/treasureBill.html",
        controller:"treasureBillController",
        files:[
            './js/treasureBill.js'
        ]
    },{
        //财富   收益账单
        name:  "treasureBill1",
        url:"/treasureBill1",
        templateUrl:"net/treasureBill1.html",
        controller:"treasureBill1Controller",
        files:[
            './js/treasureBill1.js'
        ]
    },{
        //财富   账单详情
        name:  "treasureBillDetail",
        url:"/treasureBillDetail?billId&billType",
        templateUrl:"net/treasureBillDetail.html",
        controller:"treasureBillDetailController",
        files:[
            './js/treasureBillDetail.js'
        ]
    },{
        //财富   消息
        name:  "treasureNews",
        url:"/treasureNews",
        templateUrl:"net/treasureNews.html",
        controller:"treasureNewsController",
        files:[
            './js/treasureNews.js'
        ]
    },{
        //财富   商家收益
        name:  "treasureBusinessIncome",
        url:"/treasureBusinessIncome",
        templateUrl:"net/treasureBusinessIncome.html",
        controller:"treasureBusinessIncomeController",
        files:[
            './js/treasureBusinessIncome.js'
        ]
    },{
        //财富   代理奖励
        name:  "treasureAgentReward",
        url:"/treasureAgentReward",
        templateUrl:"net/treasureAgentReward.html",
        controller:"treasureAgentRewardController",
        files:[
            './js/treasureAgentReward.js'
        ]
    },{
        //财富   辖区会员收益
        name:  "treasurePME",
        url:"/treasurePME",
        templateUrl:"net/treasurePrecinctME.html",
        controller:"treasurePMEController",
        files:[
            './js/treasurePrecinctME.js'
        ]
    },{
        //财富   辖区商家收益
        name:  "treasureJurisdictionE",
        url:"/treasureJurisdictionE",
        templateUrl:"net/treasureJurisdictionE.html",
        controller:"treasureJurisdictionEController",
        files:[
            './js/treasureJurisdictionE.js'
        ]
    },{
        //财富   统计报表
        name:  "treasureStatisticalReports",
        url:"/treasureStatisticalReports",
        templateUrl:"net/treasureStatisticalReports.html",
        controller:"treasureStatisticalReportsController",
        files:[
            './js/treasureStatisticalReports.js'
        ]
    },{
        //财富   商家货款积分明细
        name:  "treasureMerchantPayment",
        url:"/treasureMerchantPayment",
        templateUrl:"net/treasureMerchantPayment.html",
        controller:"treasureMerchantPaymentController",
        files:[
            './js/treasureMerchantPayment.js'
        ]
    },{
        //财富   商家赠送积分明细
        name:  "treasureMerchantGiving",
        url:"/treasureMerchantGiving",
        templateUrl:"net/treasureMerchantGiving.html",
        controller:"treasureMerchantGivingController",
        files:[
            './js/treasureMerchantGiving.js'
        ]
    },{
        //财富   提现
        name:  "treasureWithdrawal",
        url:"/treasureWithdrawal?id&name&num",
        templateUrl:"net/treasureWithdrawal.html",
        controller:"treasureWithdrawalController",
        files:[
            './js/treasureWithdrawal.js'
        ]
    },{
        //财富   提现明细
        name:  "treasureWithdrawalDetail",
        url:"/treasureWithdrawalDetail",
        templateUrl:"net/treasureWithdrawalDetail.html",
        controller:"treasureWithdrawalDetailController",
        files:[
            './js/treasureWithdrawalDetail.js'
        ]

    },{
        //忘记登陆密码1
        name:  "forgetPW1",
        url:"/forgetPW1",
        templateUrl:"net/forgetPW1.html",
        controller:"forgetPW1Controller",
        files:[
            './js/forgetPW1.js'
        ]
    },{
        //忘记登陆密码2
        name:  "forgetPW2",
        url:"/forgetPW2",
        templateUrl:"net/forgetPW2.html",
        controller:"forgetPW2Controller",
        files:[
            './js/forgetPW2.js'
        ]
    },{
        //忘记支付密码1
        name:  "forgetPWPay1",
        url:"/forgetPWPay1",
        templateUrl:"net/forgetPWPay1.html",
        controller:"forgetPWPay1Controller",
        files:[
            './js/forgetPWPay1.js'
        ]
    },{
        //忘记支付密码2
        name:  "forgetPWPay2",
        url:"/forgetPWPay2",
        templateUrl:"net/forgetPWPay2.html",
        controller:"forgetPWPay2Controller",
        files:[
            './js/forgetPWPay2.js'
        ]

    },{
        name:"set",
        url:"/_set",
        templateUrl:"net/set.html",
        controller:"",
        files:[]
    },{
        name:"manageBandCard",
        url:"/_manageBandCard",
        templateUrl:"net/manageBandCard.html",
        controller:"manageBandCardController",
        files:[
            './js/manageBandCardCtrl.js'
        ]
    },{
        name:"addBandCard",
        url:"/_addBandCard",
        templateUrl:"net/addBandCard.html",
        controller:"addBandCardController",
        files:[
            './js/addBandCard.js'
        ]
    },
    {
        name:"personalData",
        url:"/_personalData",
        templateUrl:"net/personalData.html",
        controller:"personalDataController",
        files:[
            './js/personalDataCtrl.js'
        ]
    },
    {
        name:"upToMerchant",
        url:"/_upToMerchant",
        templateUrl:"net/upToMerchant.html",
        controller:"upToMerchantController",
        files:[
            './js/upToMerchantCtrl.js'
        ]
    },
    {
        name:"merchantAudit",
        url:"/_merchantAudit",
        templateUrl:"net/merchantAudit.html",
        controller:"merchantAuditController",
        files:[
            './js/merchantAuditCtrl.js'
        ]
    },
    {
        name:"buyIntegral",
        url:"/_buyIntegral",
        templateUrl:"net/buyIntegral.html",
        controller:"buyIntegralController",
        files:[
            './js/buyIntegralCtrl.js'
        ]
    },
    {
        name:"sendIntegral",
        url:"/_sendIntegral",
        templateUrl:"net/sendIntegral.html",
        controller:"sendIntegralController",
        files:[
            './js/sendIntegralCtrl.js'
        ]
    },
    {
        name:"merchantAddGoods",
        url:"/_merchantAddGoods",
        templateUrl:"net/merchantAddGoods.html",
        controller:"merchantAddGoodsController",
        files:[
            './js/merchantAddGoodsCtrl.js'
        ]
    },
    {
        name:"sendIntegralOrder",
        url:"/_sendIntegralOrder?sP&uP&uN",
        templateUrl:"net/sendIntegralOrder.html",
        controller:"sendIntegralOrderController",
        files:[
            './js/sendIntegralOrderCtrl.js'
        ]
    },
    {
        name:"buyAndSendIntegralDetail",
        url:"/_buyAndSendIntegralDetail",
        templateUrl:"net/buyAndSendIntegralDetail.html",
        controller:"buyAndSendIntegralDetailController",
        files:[
            './js/buyAndSendIntegralDetailCtrl.js'
        ]
    },
    {
        name:"register",
        url:"/_registerController",
        templateUrl:"net/register.html",
        controller:"registerController",
        files:[
            './js/registerCtrl.js'
        ]
    }
]);