/*
*
*
* */
"use strict"
yx_mallApp.constant('RouterList_Config',[
    {
        name:"tabs",
        url:"/tabs",
        templateUrl:"net/tab.html",
        controller:"tabController",
        files:[
            './js/tabCtrl.js'
        ]
    },{
        name:"tabs.index",
        url:"/_index",
        templateUrl:"net/index.html",
        controller:"indexController",
        files:[
            './js/indexCtrl.js'
        ]
    },{
        name:"tabs.classify",
        url:"/_classify",
        templateUrl:"net/classify.html",
        controller:"classifyController",
        files:[
            './js/classifyCtrl.js'
        ]
    },
    {
        name:"tabs.my",
        url:"_my",
        templateUrl:"net/my.html",
        controller:"myController",
        files:[
            './js/myCtrl.js'
        ]
    },{
        name:"tabs.myOld",
        url:"_myOld",
        templateUrl:"net/my_suge.html",
        controller:"myOldController",
        files:[
            './js/myOldCtrl.js'
        ]
    },{
        name:"tabs.shopCar",
        url:"_shopCar",
        templateUrl:"net/shopCar.html",
        controller:"shopCarController",
        files:[
            './js/shop_carCtrl.js'
        ]
    },{
        name:"tabs.alliance",  //联盟商家
        url:"_alliance",
        templateUrl:"net/allianceMerchant.html",
        controller:"allianceMerchantController",
        files:[
            './js/allianceMerchant.js'

        ]
    },{
        name:"merchantClassify",//商家分类
        url:"/_merchantClassify?classifyId",
        templateUrl:"net/merchantsClassify.html",
        controller:"merchantClassifyController",
        files:[
            './js/merchantClassify.js'
        ]
    },{
        name:"treasure",    //财富
        url:"/_treasure",
        templateUrl:"net/treasure.html",
        controller:"treasureController",
        files:[
            './js/treasure.js'
        ]
    },{
        name:"classifyDetail",
        url:"/_classifyDetail?classifyId",
        templateUrl:"net/classifyDetail.html",
        controller:"classifyDetailController",
        files:[
            './js/classifyDetailCtrl.js'
        ]
    },{
        name:"detail",
        url:"/_detail?goodsId",
        templateUrl:"net/detail.html",
        controller:"detailController",
        files:[
            './js/detailCtrl.js'
        ]
    },{
        name:"clearing",
        url:"/_clearing?way",
        templateUrl:"net/clearing.html",
        controller:"clearController",
        files:[
            './js/clearCtrl.js'
        ]
    },{
        name:"login",
        url:"/_login",
        templateUrl:"net/login.html",
        controller:"loginController",
        files:[
            './js/loginCtrl.js'
        ]
    },{
        name:"applyWay",
        url:"/_applyWay?OrderID&num&price&point&sc_id&isY",
        templateUrl:"net/applyWay.html",
        controller:"applyWayController",
        files:[
            './js/applyWayCtrl.js'
        ]
    },{
        name:"address",
        url:"/_address?url",
        templateUrl:"net/address.html",
        controller:"addressController",
        files:[
            './js/addressCtrl.js'
        ]
    },{
        name:"addAddress",
        url:"/_addAddress?url",
        templateUrl:"net/addAddress.html",
        controller:"addAddressController",
        files:[
            './js/addAddressCtrl.js'
        ]
    },{
        name:"search",
        url:"/_search",
        templateUrl:"net/search.html",
        controller:"searchController",
        files:[
            './js/searchCtrl.js'
        ]
    },{
        name:"searchDetail",
        url:"/_searchDetail?goodsClass",
        templateUrl:"net/searchDetail.html",
        controller:"searchDetailController",
        files:[
            './js/searchDetailCtrl.js'
        ]
    },{
        name:"myOrder",
        url:"/_myOrder",
        templateUrl:"net/myOrder.html",
        controller:"myOrderController",
        files:[
            './js/myOrderCtrl.js'
        ]
    },{
        name:"aboutUs",
        url:"/_aboutUs",
        templateUrl:"net/aboutUs.html",
        controller:"",
        files:[]
    },{
        name:"upgrade",
        url:"/_upgrade",
        templateUrl:"net/upgrade.html",
        controller:"",
        files:[]
    },
    {
        //联盟订单 审核
        name:"allianceOrderAudit",
        url:"/_allianceOrderAudit",
        templateUrl:"net/allianceOrderAudit.html",
        controller:"allianceOrderAuditController",
        files:[
            './js/allianceOrderAuditCtrl.js'
        ]
    },{
        name:"myGoodsWithdrawal", //我的货款提现
        url:"/_myGoodsWithdrawal?id&name&num",
        templateUrl:"net/myGoodsWithdrawal.html",
        controller:"myGoodsWithdrawalController",
        files:[
            './js/myGoodsWithdrawal.js'
        ]
    },{
        //我的  货款 提现明细
        name:  "myWithdrawalDetail",
        url:"/myWithdrawalDetail",
        templateUrl:"net/myWithdrawalDetail.html",
        controller:"myWithdrawalDetailController",
        files:[
            './js/myWithdrawalDetail.js'
        ]
    },{
        //我的  积分发送明细
        name:  "myIntegralDetail",
        url:"/myIntegralDetail",
        templateUrl:"net/myIntegralDetail.html",
        controller:"myIntegralDetailController",
        files:[
            './js/myIntegralDetail.js'
        ]
    },{
        //我的  货款 收入明细
        name:  "myIncomeDetail",
        url:"/myIncomeDetail",
        templateUrl:"net/myIncomeDetail.html",
        controller:"myIncomeDetailController",
        files:[
            './js/myIncomeDetail.js'
        ]
    },{
        name:"treasureConversion", //财富  转化
        url:"/_treasureConversion",
        templateUrl:"net/treasureConversion.html",
        controller:"treasureConversionController",
        files:[
            './js/treasureConversion.js'
        ]
    },{
        name:"merchantDetail",//商家 详情
        url:"/_merchantDetail?shopId",
        templateUrl:"net/merchantsDetail.html",
        controller:"merchantDetailController",
        files:[
            './js/merchantDetail.js'
        ]
    },{
        name:"treasurePay",//支付记录
        url:"/_treasurePay",
        templateUrl:"net/treasurePay.html",
        controller:"treasurePayController",
        files:[
            './js/treasurePay.js'
        ]
    },{
        //财富   获赠积分
        name:  "treasureGiven",
        url:"/_treasureGiven",
        templateUrl:"net/treasureGiven.html",
        controller:"treasureGivenController",
        files:[
            './js/treasureGiven.js'
        ]
    },{
        //财富   会员奖励
        name:  "treasureReward",
        url:"/treasureReward",
        templateUrl:"net/treasureReward.html",
        controller:"treasureRewardController",
        files:[
            './js/treasureReward.js'
        ]
    },{
        //财富   购物账单
        name:  "treasureBill",
        url:"/treasureBill",
        templateUrl:"net/treasureBill.html",
        controller:"treasureBillController",
        files:[
            './js/treasureBill.js'
        ]
    },{
        //财富   收益账单
        name:  "treasureBill1",
        url:"/treasureBill1",
        templateUrl:"net/treasureBill1.html",
        controller:"treasureBill1Controller",
        files:[
            './js/treasureBill1.js'
        ]
    },{
        //财富   账单详情
        name:  "treasureBillDetail",
        url:"/treasureBillDetail?billId&billType",
        templateUrl:"net/treasureBillDetail.html",
        controller:"treasureBillDetailController",
        files:[
            './js/treasureBillDetail.js'
        ]
    },{
        //财富   消息
        name:  "treasureNews",
        url:"/treasureNews",
        templateUrl:"net/treasureNews.html",
        controller:"treasureNewsController",
        files:[
            './js/treasureNews.js'
        ]
    },{
        //财富   商家收益
        name:  "treasureBusinessIncome",
        url:"/treasureBusinessIncome",
        templateUrl:"net/treasureBusinessIncome.html",
        controller:"treasureBusinessIncomeController",
        files:[
            './js/treasureBusinessIncome.js'
        ]
    },{
        //财富   代理奖励
        name:  "treasureAgentReward",
        url:"/treasureAgentReward",
        templateUrl:"net/treasureAgentReward.html",
        controller:"treasureAgentRewardController",
        files:[
            './js/treasureAgentReward.js'
        ]
    },{
        //财富   辖区会员收益
        name:  "treasurePME",
        url:"/treasurePME",
        templateUrl:"net/treasurePrecinctME.html",
        controller:"treasurePMEController",
        files:[
            './js/treasurePrecinctME.js'
        ]
    },{
        //财富   辖区商家收益
        name:  "treasureJurisdictionE",
        url:"/treasureJurisdictionE",
        templateUrl:"net/treasureJurisdictionE.html",
        controller:"treasureJurisdictionEController",
        files:[
            './js/treasureJurisdictionE.js'
        ]
    },{
        //财富   统计报表
        name:  "treasureStatisticalReports",
        url:"/treasureStatisticalReports",
        templateUrl:"net/treasureStatisticalReports.html",
        controller:"treasureStatisticalReportsController",
        files:[
            './js/treasureStatisticalReports.js'
        ]
    },{
        //财富   商家货款积分明细
        name:  "treasureMerchantPayment",
        url:"/treasureMerchantPayment",
        templateUrl:"net/treasureMerchantPayment.html",
        controller:"treasureMerchantPaymentController",
        files:[
            './js/treasureMerchantPayment.js'
        ]
    },{
        //财富   商家赠送积分明细
        name:  "treasureMerchantGiving",
        url:"/treasureMerchantGiving",
        templateUrl:"net/treasureMerchantGiving.html",
        controller:"treasureMerchantGivingController",
        files:[
            './js/treasureMerchantGiving.js'
        ]
    },{
        //财富   提现
        name:  "treasureWithdrawal",
        url:"/treasureWithdrawal?id&name&num",
        templateUrl:"net/treasureWithdrawal.html",
        controller:"treasureWithdrawalController",
        files:[
            './js/treasureWithdrawal.js'
        ]
    },{
        //财富   提现明细
        name:  "treasureWithdrawalDetail",
        url:"/treasureWithdrawalDetail",
        templateUrl:"net/treasureWithdrawalDetail.html",
        controller:"treasureWithdrawalDetailController",
        files:[
            './js/treasureWithdrawalDetail.js'
        ]

    },{
        //忘记登陆密码1
        name:  "forgetPW1",
        url:"/forgetPW1",
        templateUrl:"net/forgetPW1.html",
        controller:"forgetPW1Controller",
        files:[
            './js/forgetPW1.js'
        ]
    },{
        //忘记登陆密码2
        name:  "forgetPW2",
        url:"/forgetPW2",
        templateUrl:"net/forgetPW2.html",
        controller:"forgetPW2Controller",
        files:[
            './js/forgetPW2.js'
        ]
    },{
        //忘记支付密码1
        name:  "forgetPWPay1",
        url:"/forgetPWPay1",
        templateUrl:"net/forgetPWPay1.html",
        controller:"forgetPWPay1Controller",
        files:[
            './js/forgetPWPay1.js'
        ]
    },{
        //忘记支付密码2
        name:  "forgetPWPay2",
        url:"/forgetPWPay2",
        templateUrl:"net/forgetPWPay2.html",
        controller:"forgetPWPay2Controller",
        files:[
            './js/forgetPWPay2.js'
        ]

    },{
        name:"set",
        url:"/_set",
        templateUrl:"net/set.html",
        controller:"setController",
        files:[
            './js/setCtrl.js'
        ]
    },{
        name:"manageBandCard",
        url:"/_manageBandCard?id",
        templateUrl:"net/manageBandCard.html",
        controller:"manageBandCardController",
        files:[
            './js/manageBandCardCtrl.js'
        ]
    },{
        name:"addBandCard",
        url:"/_addBandCard",
        templateUrl:"net/addBandCard.html",
        controller:"addBandCardController",
        files:[
            './js/addBandCard.js'
        ]
    },
    {
        name:"personalData",
        url:"/_personalData",
        templateUrl:"net/personalData.html",
        controller:"personalDataController",
        files:[
            './js/personalDataCtrl.js'
        ]
    },
    {
        name:"upToMerchant",
        url:"/_upToMerchant?type",
        templateUrl:"net/upToMerchant.html",
        controller:"upToMerchantController",
        files:[
            './js/upToMerchantCtrl.js'
        ]
    },
    {
        name:"merchantAudit",
        url:"/_merchantAudit",
        templateUrl:"net/merchantAudit.html",
        controller:"merchantAuditController",
        files:[
            './js/merchantAuditCtrl.js'
        ]
    },
    {
        name:"buyIntegral",
        url:"/_buyIntegral",
        templateUrl:"net/buyIntegral.html",
        controller:"buyIntegralController",
        files:[
            './js/buyIntegralCtrl.js'
        ]
    },
    {
        name:"sendIntegral",
        url:"/_sendIntegral",
        templateUrl:"net/sendIntegral.html",
        controller:"sendIntegralController",
        files:[
            './js/sendIntegralCtrl.js'
        ]
    },
    {
        name:"merchantAddGoods",
        url:"/_merchantAddGoods",
        templateUrl:"net/merchantAddGoods.html",
        controller:"merchantAddGoodsController",
        files:[
            './js/merchantAddGoodsCtrl.js'
        ]
    },
    {
        name:"sendIntegralOrder",
        url:"/_sendIntegralOrder?sP&uP&uN",
        templateUrl:"net/sendIntegralOrder.html",
        controller:"sendIntegralOrderController",
        files:[
            './js/sendIntegralOrderCtrl.js'
        ]
    },
    {
        name:"buyAndSendIntegralDetail",
        url:"/_buyAndSendIntegralDetail?way",
        templateUrl:"net/buyAndSendIntegralDetail.html",
        controller:"buyAndSendIntegralDetailController",
        files:[
            './js/buyAndSendIntegralDetailCtrl.js'
        ]
    },
    {
        name:"register",
        url:"/_register",
        templateUrl:"net/register.html",
        controller:"registerController",
        files:[
            './js/registerCtrl.js'
        ]
    },
    {
        name:"myMember",//我的会员
        url:"/_myMember?role",
        templateUrl:"net/myMember.html",
        controller:"myMemberController",
        files:[
            './js/myMemberCtrl.js'
        ]
    },
    {
        name:"scanApply",//扫码支付
        url:"/_scanApply",
        templateUrl:"net/scanApply.html",
        controller:"scanApplyController",
        files:[
            './js/scanApplyCtrl.js'
        ]
    },
    {
        name:"allianceOrder",//联盟订单
        url:"/_allianceOrder",
        templateUrl:"net/allianceOrder.html",
        controller:"allianceOrderController",
        files:[
            './js/allianceOrderCtrl.js'
        ]
    },
    {
        name:"applyReturnGoods",//申请退货
        url:"/_applyReturnGoods",
        templateUrl:"net/applyReturnGoods.html",
        controller:"applyReturnGoodsController",
        files:[
            './js/applyReturnGoodsCtrl.js'
        ]
    },
    {
        name:"merchantOrder",//商家订单
        url:"/_merchantOrder",
        templateUrl:"net/merchantOrder.html",
        controller:"merchantOrderController",
        files:[
            './js/merchantOrderCtrl.js'
        ]
    },
    {
        name:"upGradeKind",//会员升级
        url:"/_upGradeKind?way",
        templateUrl:"net/upGradeKind.html",
        controller:"upGradeKindController",
        files:[
            './js/upGradeKindCtrl.js'
        ]
    },
    {
        name:"integralReceive",//积分迁入
        url:"/_integralReceive",
        templateUrl:"net/integralReceive.html",
        controller:"integralReceiveController",
        files:[
            './js/integralReceiveCtrl.js'
        ]
    },
    {
        name:"commentsAndFeedback",//意见与反馈
        url:"/_commentsAndFeedback",
        templateUrl:"net/commentsAndFeedback.html",
        controller:"commentsAndFeedbackController",
        files:[
            './js/commentsAndFeedbackCtrl.js'
        ]
    },
    {
        name:"cashIntegral",// 现金积分
        url:"/_cashIntegral",
        templateUrl:"net/cashIntegral.html",
        controller:"cashIntegralController",
        files:[
            './js/cashIntegralCtrl.js'
        ]
    },
    {
        name:"cashIntegralChangeRecord",//现金积分转化记录
        url:"/_cashIntegralChangeRecord",
        templateUrl:"net/cashIntegralChangeRecord.html",
        controller:"cashIntegralChangeRecordController",
        files:[
            './js/cashIntegralChangeRecordCtrl.js'
        ]
    },
    {
        name:"cashIntegralConsumptionRecord",// 现金积分消费积分
        url:"/_cashIntegralConsumptionRecord",
        templateUrl:"net/cashIntegralConsumptionRecord.html",
        controller:"cashIntegralConsumptionRecordController",
        files:[
            './js/cashIntegralConsumptionRecordCtrl.js'
        ]
    },
    {
        name:"cashIntegralWithdrawal",// 现金积分提现
        url:"/_cashIntegralWithdrawal",
        templateUrl:"net/cashIntegralWithdrawal.html",
        controller:"cashIntegralWithdrawalController",
        files:[
            './js/cashIntegralWithdrawalCtrl.js'
        ]
    },
    {
        name:"cashIntegralWithdrawalRecord",// 现金积分提现记录
        url:"/_cashIntegralWithdrawalRecord",
        templateUrl:"net/cashIntegralWithdrawalRecord.html",
        controller:"cashIntegralWithdrawalRecordController",
        files:[
            './js/cashIntegralWithdrawalRecordCtrl.js'
        ]
    },
    {
        name:"shopIntegral",//购物积分专区
        url:"/_shopIntegral",
        templateUrl:"net/shopIntegral.html",
        controller:"shopIntegralController",
        files:[
            './js/shopIntegralCtrl.js'
        ]
    },
    {
        name:"shopIntegralGoodsDetail",//购物积分专区
        url:"/_shopIntegralGoodsDetail?goodsId",
        templateUrl:"net/shopIntegralGoodsDetail.html",
        controller:"shopIntegralGoodsDetailController",
        files:[
            './js/shopIntegralGoodsDetailCtrl.js'
        ]
    },
    {
        name:"coupons",// 优惠券
        url:"/_coupons",
        templateUrl:"net/coupons.html",
        controller:"couponsController",
        files:[
            './js/couponsCtrl.js'
        ]
    },
    {
        name:"myCoupons",// 我的优惠券
        url:"/_myCoupons",
        templateUrl:"net/myCoupons.html",
        controller:"myCouponsController",
        files:[
            './js/myCouponsCtrl.js'
        ]
    },
    {
        name:"sendCoupons",// 我的优惠券
        url:"/_sendCoupons",
        templateUrl:"net/sendCoupons.html",
        controller:"sendCouponsController",
        files:[
            './js/sendCouponsCtrl.js'
        ]
    },
    {
        name:"haveSendCoupons",// 已发送优惠券
        url:"/_haveSendCoupons",
        templateUrl:"net/haveSendCoupons.html",
        controller:"haveSendCouponsController",
        files:[
            './js/haveSendCouponsCtrl.js'
        ]
    }

]);