/*
*
*
* */
"use strict"
yx_mallApp.constant('RouterList_Config',[
    {
        name:"tabs",
        url:"/tabs",
        templateUrl:"net/tab.html",
        controller:"tabController",
        files:[
            './js/tabCtrl.js'
        ]
    },{
        name:"tabs.index",
        url:"/_index",
        templateUrl:"net/index.html",
        controller:"indexController",
        files:[
            './js/indexCtrl.js'
        ]
    },{
        name:"tabs.classify",
        url:"/_classify",
        templateUrl:"net/classify.html",
        controller:"classifyController",
        files:[
            './js/classifyCtrl.js'
        ]
    },
    {
        name:"tabs.my",
        url:"_my",
        templateUrl:"net/my.html",
        controller:"myController",
        files:[
            './js/myCtrl.js'
        ]
    },{
        name:"tabs.myOld",
        url:"_myOld",
        templateUrl:"net/my_suge.html",
        controller:"myOldController",
        files:[
            './js/myOldCtrl.js'
        ]
    },{
        name:"tabs.shopCar",
        url:"_shopCar",
        templateUrl:"net/shopCar.html",
        controller:"shopCarController",
        files:[
            './js/shop_carCtrl.js'
        ]
    },{
        name:"tabs.alliance",
        url:"_alliance",
        templateUrl:"net/allianceMerchant.html",
        controller:"allianceMerchantController",
        files:[
            './js/allianceMerchant.js'
        ]
    },{
        name:"merchantClassify",
        url:"/_merchantClassify",
        templateUrl:"net/merchantsClassify.html",
        controller:"merchantClassifyController",
        files:[
            './js/merchantClassify.js'
        ]
    },{
        name:"treasure",
        url:"/_treasure",
        templateUrl:"net/treasure.html",
        controller:"treasureController",
        files:[
            './js/treasure.js'
        ]
    },{
        name:"classifyDetail",
        url:"/_classifyDetail?classifyId",
        templateUrl:"net/classifyDetail.html",
        controller:"classifyDetailController",
        files:[
            './js/classifyDetailCtrl.js'
        ]
    },{
        name:"detail",
        url:"/_detail?goodsId",
        templateUrl:"net/detail.html",
        controller:"detailController",
        files:[
            './js/detailCtrl.js'
        ]
    },{
        name:"clearing",
        url:"/_clearing",
        templateUrl:"net/clearing.html",
        controller:"clearController",
        files:[
            './js/clearCtrl.js'
        ]
    },{
        name:"login",
        url:"/_login",
        templateUrl:"net/login.html",
        controller:"loginController",
        files:[
            './js/loginCtrl.js'
        ]
    },{
        name:"applyWay",
        url:"/_applyWay?OrderID&num&price&point",
        templateUrl:"net/applyWay.html",
        controller:"applyWayController",
        files:[
            './js/applyWayCtrl.js'
        ]
    },{
        name:"address",
        url:"/_address",
        templateUrl:"net/address.html",
        controller:"addressController",
        files:[
            './js/addressCtrl.js'
        ]
    },{
        name:"addAddress",
        url:"/_addAddress",
        templateUrl:"net/addAddress.html",
        controller:"addAddressController",
        files:[
            './js/addAddressCtrl.js'
        ]
    },{
        name:"search",
        url:"/_search",
        templateUrl:"net/search.html",
        controller:"searchController",
        files:[
            './js/searchCtrl.js'
        ]
    },{
        name:"searchDetail",
        url:"/_searchDetail?goodsClass",
        templateUrl:"net/searchDetail.html",
        controller:"searchDetailController",
        files:[
            './js/searchDetailCtrl.js'
        ]
    },{
        name:"myOrder",
        url:"/_myOrder",
        templateUrl:"net/myOrder.html",
        controller:"myOrderController",
        files:[
            './js/myOrderCtrl.js'
        ]
    },{
        name:"upgrade",
        url:"/_upgrade",
        templateUrl:"net/upgrade.html",
        controller:"",
        files:[]
    },{
        name:"treasureConversion",
        url:"/_treasureConversion",
        templateUrl:"net/treasureConversion.html",
        controller:"treasureConversionController",
        files:[
            './js/treasureConversion.js'
        ]
    },{
        name:"set",
        url:"/_set",
        templateUrl:"net/set.html",
        controller:"",
        files:[]
    },{
        name:"manageBandCard",
        url:"/_manageBandCard",
        templateUrl:"net/manageBandCard.html",
        controller:"manageBandCardController",
        files:[
            './js/manageBandCardCtrl.js'
        ]
    },{
        name:"addBandCard",
        url:"/_addBandCard",
        templateUrl:"net/addBandCard.html",
        controller:"addBandCardController",
        files:[
            './js/addBandCard.js'
        ]
    },
    {
        name:"personalData",
        url:"/_personalData",
        templateUrl:"net/personalData.html",
        controller:"personalDataController",
        files:[
            './js/personalDataCtrl.js'
        ]
    },
    {
        name:"upToMerchant",
        url:"/_upToMerchant",
        templateUrl:"net/upToMerchant.html",
        controller:"upToMerchantController",
        files:[
            './js/upToMerchantCtrl.js'
        ]
    },
    {
        name:"merchantAudit",
        url:"/_merchantAudit",
        templateUrl:"net/merchantAudit.html",
        controller:"merchantAuditController",
        files:[
            './js/merchantAuditCtrl.js'
        ]
    },
    {
        name:"buyIntegral",
        url:"/_buyIntegral",
        templateUrl:"net/buyIntegral.html",
        controller:"buyIntegralController",
        files:[
            './js/buyIntegralCtrl.js'
        ]
    },
    {
        name:"sendIntegral",
        url:"/_sendIntegral",
        templateUrl:"net/sendIntegral.html",
        controller:"sendIntegralController",
        files:[
            './js/sendIntegralCtrl.js'
        ]
    },
    {
        name:"merchantAddGoods",
        url:"/_merchantAddGoods",
        templateUrl:"net/merchantAddGoods.html",
        controller:"merchantAddGoodsController",
        files:[
            './js/merchantAddGoodsCtrl.js'
        ]
    },
    {
        name:"sendIntegralOrder",
        url:"/_sendIntegralOrder?sP&uP&uN",
        templateUrl:"net/sendIntegralOrder.html",
        controller:"sendIntegralOrderController",
        files:[
            './js/sendIntegralOrderCtrl.js'
        ]
    },
    {
        name:"buyAndSendIntegralDetail",
        url:"/_buyAndSendIntegralDetail",
        templateUrl:"net/buyAndSendIntegralDetail.html",
        controller:"buyAndSendIntegralDetailController",
        files:[
            './js/buyAndSendIntegralDetailCtrl.js'
        ]
    }
    ,
    {
        name:"allianceOrderAudit",
        url:"/_allianceOrderAudit",
        templateUrl:"net/allianceOrderAudit.html",
        controller:"allianceOrderAuditController",
        files:[
            './js/allianceOrderAuditCtrl.js'
        ]
    }
]);